---
name: Deploy to prod environment

on:
  pull_request_target:
    branches:
      - main  # Deploy to prod environment

jobs: 
  deploy:
    name: Deploy Application
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          fi

      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

      - name: Copy project to VPS
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USER }}/${{ secrets.APP_NAME }}-${{ env.DEPLOY_ENV }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd /home/${{ secrets.VPS_USER }}/${{ secrets.APP_NAME }}-${{ env.DEPLOY_ENV }}
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d app-${{ env.DEPLOY_ENV }}
          EOF
